"use strict";
// auto-generated by `jswt reexport`
// DO NOT EDIT

module.exports = require("./libreoffice-as-a-service.js")

// these typedef reexports will be available to dependent packages
/**
 */
